### ISSUE TITLE
Spark submit: wrong path to script

### ISSUE THREAD

**Issue by ericbolo** [thomhopmans/themarketingtechnologist#1]
Thanks for the great resources, Mr Hopmans!

While running your boto3 scripts for AWS EMR + Spark, I noticed the path to the script was wrong in the following function:

def step_spark_submit(self, c, arguments):
        """
        :param c:
        :return:
        """
        response = c.add_job_flow_steps(
            JobFlowId=self.job_flow_id,
            Steps=[
                {
                    'Name': 'Spark Application',
                    'ActionOnFailure': 'CONTINUE',
                    'HadoopJarStep': {
                        'Jar': 'command-runner.jar',
                        'Args': [
                            "spark-submit",
                            "/home/hadoop/run.py",
                            arguments
                        ]
                    }
                },
            ]
        )
        logger.info("Added step 'spark-submit' with argument '{}'".format(arguments))
        time.sleep(1)  # Prevent ThrottlingException

Running it as is causes an error during step execution.

Replacing "/home/hadoop/run.py" with "/home/hadoop/wordcount.py" fixes it.

**Comment by thomhopmans** [comment]
Thanks @ericbolo, I just pushed the fix 👍
